sudo: false
language: python
cache: pip

matrix:
  include:
    - python: 3.4
      env: TF_BINARY_URL=https://storage.googleapis.com/tensorflow/linux/cpu/tensorflow-0.11.0-cp34-cp34m-linux_x86_64.whl

    - python: 2.7
      env: TF_BINARY_URL=https://storage.googleapis.com/tensorflow/linux/cpu/tensorflow-0.11.0-cp27-none-linux_x86_64.whl

install:
  - pip install --upgrade pip
  - pip install --upgrade $TF_BINARY_URL
  - pip install --only-binary=numpy,scipy numpy scipy
  - pip install --only-binary=numpy,scipy -r requirements.txt

script:
  - cd wideep && python net_mk1.py
  
